version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - /home/will/srv/services/jellyfin/config:/config
      - /var/cache/jellyfin:/cache
      - type: bind
        source: /media
        target: /media
      - type: bind
        source: /media2
        target: /media2
        read_only: true
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://will-crockett.com/jellyfin
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - media-network
networks:
  media-network:
