services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./config:/config
      - ~/srv/share_media:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - media
networks:
  media:
    external: true

