services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./config:/config
      - /media:/movies
      - ~/srv/services/qbittorrent/content/torrents:/downloads
    network_mode: bridge
    ports:
      - 7878:7878
    restart: unless-stopped

