services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./config:/config
      - ~/srv/share_media:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - media
networks:
  media:
    external: true
