services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /media2:/data
      - ./config:/config
      - ~/srv/services/qbittorrent/content/torrents:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
networks:
  media-network:
