services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - media
networks:
  media:
    external: true
