services:
  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./config:/config
      - ~/srv/services/qbittorrent/content/torrents:/downloads
    network_mode: bridge
    ports:
      - 9117:9117
    restart: unless-stopped
